CREATE OR REPLACE PACKAGE PKG_OCENY AS

    FUNCTION SREDNIA_STUDENTA(
        P_ID_STUDENTA NUMBER
    ) RETURN NUMBER;

    PROCEDURE RANKING_STUDENTOW;

    PROCEDURE SPRAWDZ_ZALICZENIE(
        P_ID_STUDENTA NUMBER
    );

END PKG_OCENY;
/

FUNCTION SREDNIA_STUDENTA(
    P_ID_STUDENTA NUMBER
)
RETURN NUMBER
IS
    V_SREDNIA NUMBER;
BEGIN

    SELECT AVG(OCENA_KONCOWA)
    INTO V_SREDNIA
    FROM OCENY_KONCOWE
    WHERE ID_STUDENTA = P_ID_STUDENTA;

    RETURN NVL(ROUND(V_SREDNIA,2),0);

END;

PROCEDURE RANKING_STUDENTOW
IS

CURSOR C_RANKING IS
SELECT
    S.ID_STUDENTA,
    S.IMIE,
    S.NAZWISKO,
    AVG(O.OCENA_KONCOWA) SREDNIA
FROM STUDENCI S
JOIN OCENY_KONCOWE O
    ON S.ID_STUDENTA = O.ID_STUDENTA
GROUP BY
    S.ID_STUDENTA,
    S.IMIE,
    S.NAZWISKO
ORDER BY SREDNIA DESC;

V_ID NUMBER;
V_IMIE VARCHAR2(50);
V_NAZWISKO VARCHAR2(100);
V_SREDNIA NUMBER;

BEGIN

    OPEN C_RANKING;

    LOOP

        FETCH C_RANKING
        INTO
            V_ID,
            V_IMIE,
            V_NAZWISKO,
            V_SREDNIA;

        EXIT WHEN C_RANKING%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            V_IMIE || ' ' ||
            V_NAZWISKO || ' : ' ||
            V_SREDNIA
        );

    END LOOP;

    CLOSE C_RANKING;

END;

PROCEDURE SPRAWDZ_ZALICZENIE(
    P_ID_STUDENTA NUMBER
)
IS

    V_SREDNIA NUMBER;

BEGIN

    V_SREDNIA :=
        SREDNIA_STUDENTA(P_ID_STUDENTA);

    IF V_SREDNIA >= 3.0 THEN

        UPDATE OCENY_KONCOWE
        SET CZY_ZALICZONO = 'T',
            DATA_ZAMKNIECIA = SYSDATE
        WHERE ID_STUDENTA = P_ID_STUDENTA;

    ELSE

        UPDATE OCENY_KONCOWE
        SET CZY_ZALICZONO = 'N',
            DATA_ZAMKNIECIA = SYSDATE
        WHERE ID_STUDENTA = P_ID_STUDENTA;

    END IF;

END;