spring.application.name=system-oceniania

# połączenie z bazą Oracle w Dockerze (konto system, port 1521, usługa FREE)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=system
spring.datasource.password=Projekt2026Haslo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# konfiguracja Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true